# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180401_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_number',
            field=models.IntegerField(choices=[(0, 1), (2, 3), (1, 2)], default=0, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Level', to_field='level_number'),
        ),
    ]
