# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Language'),
        ),
    ]
