# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='qwerty', max_length=200),
            preserve_default=False,
        ),
    ]
